신경망 구조 생성

In [1]:
#iris dataset load
from sklearn import datasets
iris = datasets.load_iris()

X = iris.data
y = iris.target

from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.3, random_state=1)

In [6]:
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Input, Dense, Dropout, PReLU, Activation, ELU

# 모델 정의
model = Sequential()
model.add(Input(shape=(4,)))
model.add(Dense(50, activation='sigmoid'))

# PReLU는 activation='PReLU' 처럼 쓰지 않고,
# Dense -> PReLU() 층을 따로 추가해야 합니다.
model.add(Dense(50))
model.add(PReLU())

model.add(Dropout(0.4))
model.add(Dense(30))
model.add(ELU(alpha=1))   # Activation(ELU()) 대신 바로 ELU() 사용 가능

model.add(Dense(3, activation='softmax'))
model.summary()

Model: "sequential_4"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━┓
┃ Layer (type)                    ┃ Output Shape           ┃       Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━┩
│ dense_3 (Dense)                 │ (None, 50)             │           250 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense_4 (Dense)                 │ (None, 50)             │         2,550 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ p_re_lu (PReLU)                 │ (None, 50)             │            50 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dropout_1 (Dropout)             │ (None, 50)             │             0 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense_5 (Dense)                 │ (None, 30)             │         1,530 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ elu (ELU)                       │ (None, 30)             │             0 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense_6 (Dense)                 │ (None, 3)              │            93 │
└─────────────────────────────────┴────────────────────────┴───────────────┘

 Total params: 4,473 (17.47 KB)

 Trainable params: 4,473 (17.47 KB)

 Non-trainable params: 0 (0.00 B)

가중치 초기화

In [9]:
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Input, Dense, Dropout, PReLU, Activation, ELU
from tensorflow.keras.initializers import RandomNormal

model1 = Sequential()
model1.add(Input(shape=(4,)))
model1.add(Dense(50, activation='sigmoid', kernel_initializer='he_normal'))
model1.add(Dense(50, activation=PReLU()))
model1.add(Dense(30, activation='sigmoid', kernel_initializer=RandomNormal(mean=0, stddev=0.1)))
model1.add(Dense(3, activation='softmax'))
model1.summary()

Model: "sequential_7"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━┓
┃ Layer (type)                    ┃ Output Shape           ┃       Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━┩
│ dense_12 (Dense)                │ (None, 50)             │           250 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense_13 (Dense)                │ (None, 50)             │         2,550 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense_14 (Dense)                │ (None, 30)             │         1,530 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense_15 (Dense)                │ (None, 3)              │            93 │
└─────────────────────────────────┴────────────────────────┴───────────────┘

 Total params: 4,423 (17.28 KB)

 Trainable params: 4,423 (17.28 KB)

 Non-trainable params: 0 (0.00 B)

배치 정규화

In [12]:
from tensorflow.keras.layers import BatchNormalization
model2 = Sequential()
model2.add(Input(shape=(4,)))
model2.add(Dense(50, activation='sigmoid'))
model2.add(BatchNormalization())
model2.add(Dense(50, activation='sigmoid'))
model2.add(BatchNormalization())
model2.add(Dense(30, activation='sigmoid'))
model2.add(BatchNormalization())
model2.add(Dense(3, activation='softmax'))
model2.summary()

Model: "sequential_8"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━┓
┃ Layer (type)                    ┃ Output Shape           ┃       Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━┩
│ dense_16 (Dense)                │ (None, 50)             │           250 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ batch_normalization             │ (None, 50)             │           200 │
│ (BatchNormalization)            │                        │               │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense_17 (Dense)                │ (None, 50)             │         2,550 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ batch_normalization_1           │ (None, 50)             │           200 │
│ (BatchNormalization)            │                        │               │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense_18 (Dense)                │ (None, 30)             │         1,530 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ batch_normalization_2           │ (None, 30)             │           120 │
│ (BatchNormalization)            │                        │               │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense_19 (Dense)                │ (None, 3)              │            93 │
└─────────────────────────────────┴────────────────────────┴───────────────┘

 Total params: 4,943 (19.31 KB)

 Trainable params: 4,683 (18.29 KB)

 Non-trainable params: 260 (1.02 KB)

컴파일

In [15]:
for model in model, model1, model2:
  model.compile(
      optimizer='adam',
      loss='sparse_categorical_crossentropy',
      metrics=['accuracy']
  )

학습


In [16]:
for model in model, model1, model2:
  model.fit(X_train, y_train, epochs=300, verbose=1)

Epoch 1/300
4/4 ━━━━━━━━━━━━━━━━━━━━ 3s 12ms/step - accuracy: 0.6545 - loss: 0.9909
Epoch 2/300
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - accuracy: 0.7492 - loss: 0.4624 
Epoch 3/300
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - accuracy: 0.8536 - loss: 0.3717
Epoch 4/300
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - accuracy: 0.9088 - loss: 0.3279 
Epoch 5/300
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - accuracy: 0.8786 - loss: 0.3205
Epoch 6/300
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - accuracy: 0.8664 - loss: 0.3217 
Epoch 7/300
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - accuracy: 0.9109 - loss: 0.2845
Epoch 8/300
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - accuracy: 0.9209 - loss: 0.2531
Epoch 9/300
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - accuracy: 0.9396 - loss: 0.2106
Epoch 10/300
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - accuracy: 0.9431 - loss: 0.2020
Epoch 11/300
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - accuracy: 0.9456 - loss: 0.1961
Epoch 12/300
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - accuracy: 0.9698 -

평가

In [19]:
for name, m in zip(["model", "model1", "model2"], [model, model1, model2]):
    loss, acc = m.evaluate(X_test, y_test, verbose=0)
    print(f"{name} → 정확도: {acc:.4f}, 손실: {loss:.4f}")

model → 정확도: 0.9333, 손실: 0.1553
model1 → 정확도: 1.0000, 손실: 0.0228
model2 → 정확도: 0.9333, 손실: 0.1553


평과 결과 비교

model1 은 가장 좋은 성능을 보이지만, 다만 너무 높은 정확도는 오버피팅일 가능성도 염두해야함

In [39]:
import pandas as pd

redwine = pd.read_csv("https://archive.ics.uci.edu/ml/machine-learning-databases/wine-quality/winequality-red.csv", sep=";")
X, y = redwine.iloc[:, :-1], redwine.iloc[:, -1]

In [40]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.3, random_state=1)

In [41]:
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Input, Dense, Dropout, PReLU, Activation, ELU
from tensorflow.keras.initializers import RandomNormal

model1 = Sequential()
model1.add(Input(shape=(11,)))
model1.add(Dense(100, activation='sigmoid'))
model1.add(Dropout(0.2))
model1.add(Dense(200, activation='relu'))
model1.add(Dropout(0.4))
model1.add(Dense(50, activation='tanh'))
model1.add(Dropout(0.1))
model1.add(Dense(6, activation='softmax'))
model1.summary()

Model: "sequential_10"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━┓
┃ Layer (type)                    ┃ Output Shape           ┃       Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━┩
│ dense_24 (Dense)                │ (None, 100)            │         1,200 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dropout_5 (Dropout)             │ (None, 100)            │             0 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense_25 (Dense)                │ (None, 200)            │        20,200 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dropout_6 (Dropout)             │ (None, 200)            │             0 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense_26 (Dense)                │ (None, 50)             │        10,050 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dropout_7 (Dropout)             │ (None, 50)             │             0 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense_27 (Dense)                │ (None, 6)              │           306 │
└─────────────────────────────────┴────────────────────────┴───────────────┘

 Total params: 31,756 (124.05 KB)

 Trainable params: 31,756 (124.05 KB)

 Non-trainable params: 0 (0.00 B)

In [42]:
from tensorflow.keras.optimizers import Adam
model1.compile(
    optimizer=Adam(learning_rate=0.001),  # 적절한 learning rate
    loss='sparse_categorical_crossentropy',
    metrics=['accuracy']
)

In [43]:
import numpy as np
print(np.unique(y_train))

[3 4 5 6 7 8]


In [44]:
y_train = y_train - y_train.min()
y_test = y_test - y_test.min()

In [45]:
model1.fit(X_train, y_train, epochs=300, batch_size = 200, verbose = 1)

Epoch 1/300
6/6 ━━━━━━━━━━━━━━━━━━━━ 2s 16ms/step - accuracy: 0.2889 - loss: 1.6413
Epoch 2/300
6/6 ━━━━━━━━━━━━━━━━━━━━ 0s 15ms/step - accuracy: 0.4109 - loss: 1.2705
Epoch 3/300
6/6 ━━━━━━━━━━━━━━━━━━━━ 0s 18ms/step - accuracy: 0.4444 - loss: 1.2543
Epoch 4/300
6/6 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - accuracy: 0.4416 - loss: 1.2160
Epoch 5/300
6/6 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - accuracy: 0.4579 - loss: 1.1995 
Epoch 6/300
6/6 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - accuracy: 0.4504 - loss: 1.1665 
Epoch 7/300
6/6 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - accuracy: 0.4706 - loss: 1.1628 
Epoch 8/300
6/6 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - accuracy: 0.4670 - loss: 1.1825 
Epoch 9/300
6/6 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - accuracy: 0.5040 - loss: 1.1691 
Epoch 10/300
6/6 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - accuracy: 0.4653 - loss: 1.1631
Epoch 11/300
6/6 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - accuracy: 0.4808 - loss: 1.1770
Epoch 12/300
6/6 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - accuracy: 0.4974 - lo

In [46]:
X_test = np.array(X_test)
y_test = np.array(y_test)

loss, accuracy = model1.evaluate(X_test, y_test)
print(f"Loss: {loss:.4f}, Accuracy: {accuracy:.4f}")

15/15 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.6304 - loss: 0.8829  
Loss: 0.9508, Accuracy: 0.6021


In [47]:
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense, Dropout

model6 = Sequential()
model6.add(Dense(64, input_shape=(11,), activation='relu'))
model6.add(Dropout(0.2))
model6.add(Dense(32, activation='relu'))
model6.add(Dropout(0.1))
model6.add(Dense(6, activation='softmax'))

/usr/local/lib/python3.12/dist-packages/keras/src/layers/core/dense.py:93: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(activity_regularizer=activity_regularizer, **kwargs)


In [48]:
from tensorflow.keras.optimizers import Adam

model6.compile(
    optimizer=Adam(learning_rate=0.001),  # 적절한 learning rate
    loss='sparse_categorical_crossentropy',
    metrics=['accuracy']
)

history = model6.fit(
    X_train, y_train,
    epochs=100,       # 너무 길면 과적합 가능
    batch_size=32,    # 일반적으로 안정적
    validation_split=0.2,  # 검증용 데이터로 성능 체크
    verbose=1
)

Epoch 1/100
28/28 ━━━━━━━━━━━━━━━━━━━━ 2s 12ms/step - accuracy: 0.0939 - loss: 10.9656 - val_accuracy: 0.4286 - val_loss: 1.7722
Epoch 2/100
28/28 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.3796 - loss: 2.8845 - val_accuracy: 0.4286 - val_loss: 1.6606
Epoch 3/100
28/28 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.4131 - loss: 2.1685 - val_accuracy: 0.4821 - val_loss: 1.3636
Epoch 4/100
28/28 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.3641 - loss: 2.2497 - val_accuracy: 0.4598 - val_loss: 1.3365
Epoch 5/100
28/28 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.3950 - loss: 1.7966 - val_accuracy: 0.4509 - val_loss: 1.2868
Epoch 6/100
28/28 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.4288 - loss: 1.6810 - val_accuracy: 0.4732 - val_loss: 1.2826
Epoch 7/100
28/28 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.3819 - loss: 1.5511 - val_accuracy: 0.4464 - val_loss: 1.2766
Epoch 8/100
28/28 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.4056 - loss: 1.4188 - val_accuracy: 0.3795 -

In [49]:
model6.fit(X_train, y_train, epochs=300, batch_size = 200, verbose = 1)

Epoch 1/300
6/6 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - accuracy: 0.5088 - loss: 1.0751 
Epoch 2/300
6/6 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.5426 - loss: 1.0793 
Epoch 3/300
6/6 ━━━━━━━━━━━━━━━━━━━━ 0s 17ms/step - accuracy: 0.5418 - loss: 1.0661 
Epoch 4/300
6/6 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.5453 - loss: 1.0623  
Epoch 5/300
6/6 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.5440 - loss: 1.0415  
Epoch 6/300
6/6 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.5261 - loss: 1.0494 
Epoch 7/300
6/6 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.5214 - loss: 1.0774  
Epoch 8/300
6/6 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - accuracy: 0.5347 - loss: 1.0721 
Epoch 9/300
6/6 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.5390 - loss: 1.0693 
Epoch 10/300
6/6 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.5293 - loss: 1.0677  
Epoch 11/300
6/6 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - accuracy: 0.5326 - loss: 1.0605 
Epoch 12/300
6/6 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.5373

In [50]:
import numpy as np
from sklearn.preprocessing import StandardScaler
from sklearn.model_selection import train_test_split
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense, Dropout
from tensorflow.keras.optimizers import Adam
from tensorflow.keras.callbacks import EarlyStopping

import pandas as pd

redwine = pd.read_csv("https://archive.ics.uci.edu/ml/machine-learning-databases/wine-quality/winequality-red.csv", sep=";")
X, y = redwine.iloc[:, :-1], redwine.iloc[:, -1]

# ----------------------------
# 1️⃣ 데이터 준비
# ----------------------------
# X, y는 기존 와인 데이터셋
# X.shape = (1119, 11), y.shape = (1119,)

# y를 0부터 시작하도록 조정
y = y - np.min(y)

# 데이터 분리 (학습 80%, 테스트 20%)
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

# 표준화 / 정규화
scaler = StandardScaler()
X_train = scaler.fit_transform(X_train)
X_test = scaler.transform(X_test)

# ----------------------------
# 2️⃣ 개선된 모델 정의
# ----------------------------
model = Sequential()
model.add(Dense(64, input_shape=(X_train.shape[1],), activation='relu'))
model.add(Dropout(0.2))
model.add(Dense(32, activation='relu'))
model.add(Dropout(0.1))
model.add(Dense(6, activation='softmax'))  # 클래스 수에 맞춤

# ----------------------------
# 3️⃣ 컴파일
# ----------------------------
model.compile(
    optimizer=Adam(learning_rate=0.001),
    loss='sparse_categorical_crossentropy',
    metrics=['accuracy']
)

# ----------------------------
# 4️⃣ 학습 (EarlyStopping 사용)
# ----------------------------
early_stop = EarlyStopping(monitor='val_loss', patience=10, restore_best_weights=True)

history = model.fit(
    X_train, y_train,
    epochs=100,
    batch_size=32,
    validation_split=0.2,
    callbacks=[early_stop],
    verbose=1
)

# ----------------------------
# 5️⃣ 평가
# ----------------------------
loss, accuracy = model.evaluate(X_test, y_test)
print(f"Loss: {loss:.4f}, Accuracy: {accuracy:.4f}")

Epoch 1/100


/usr/local/lib/python3.12/dist-packages/keras/src/layers/core/dense.py:93: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(activity_regularizer=activity_regularizer, **kwargs)


32/32 ━━━━━━━━━━━━━━━━━━━━ 2s 12ms/step - accuracy: 0.1968 - loss: 1.7310 - val_accuracy: 0.5547 - val_loss: 1.3181
Epoch 2/100
32/32 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.5197 - loss: 1.3185 - val_accuracy: 0.6328 - val_loss: 1.0443
Epoch 3/100
32/32 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.5538 - loss: 1.1553 - val_accuracy: 0.6445 - val_loss: 0.9504
Epoch 4/100
32/32 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.5844 - loss: 1.0901 - val_accuracy: 0.6523 - val_loss: 0.9242
Epoch 5/100
32/32 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.5982 - loss: 1.0385 - val_accuracy: 0.6602 - val_loss: 0.9046
Epoch 6/100
32/32 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.5767 - loss: 1.0404 - val_accuracy: 0.6602 - val_loss: 0.8957
Epoch 7/100
32/32 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.5510 - loss: 1.0394 - val_accuracy: 0.6602 - val_loss: 0.8932
Epoch 8/100
32/32 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.5444 - loss: 1.0473 - val_accuracy: 0.6641 - val_loss: 0.

In [52]:
# ----------------------------
# 1️⃣ 라이브러리 불러오기
# ----------------------------
import numpy as np
from sklearn.ensemble import RandomForestClassifier
from sklearn.model_selection import train_test_split, cross_val_score
from sklearn.preprocessing import StandardScaler
from sklearn.metrics import accuracy_score, classification_report, confusion_matrix

# ----------------------------
# 2️⃣ 데이터 준비
# ----------------------------
# X, y는 와인 데이터셋
# X.shape = (1119, 11), y.shape = (1119,)

# y를 0부터 시작하도록 조정
y = y - np.min(y)

# 데이터 분리 (학습 80%, 테스트 20%)
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42, stratify=y)

# 표준화 / 정규화
scaler = StandardScaler()
X_train = scaler.fit_transform(X_train)
X_test = scaler.transform(X_test)

# ----------------------------
# 3️⃣ RandomForest 모델 정의 및 학습
# ----------------------------
rf = RandomForestClassifier(
    n_estimators=500,
    max_depth=10,
    min_samples_split=5,
    max_features='sqrt',
    random_state=42,
    n_jobs=-1
)

# 학습
rf.fit(X_train, y_train)

# ----------------------------
# 4️⃣ 예측 및 평가
# ----------------------------
y_pred = rf.predict(X_test)

accuracy = accuracy_score(y_test, y_pred)
print(f"Test Accuracy: {accuracy:.4f}\n")

print("Classification Report:")
print(classification_report(y_test, y_pred))

print("Confusion Matrix:")
print(confusion_matrix(y_test, y_pred))

# ----------------------------
# 5️⃣ 교차 검증 (선택)
# ----------------------------
cv_scores = cross_val_score(rf, X_train, y_train, cv=5, scoring='accuracy')
print(f"5-Fold CV Accuracy: {cv_scores.mean():.4f}")

Test Accuracy: 0.6844

Classification Report:
              precision    recall  f1-score   support

           0       0.00      0.00      0.00         2
           1       0.00      0.00      0.00        11
           2       0.72      0.76      0.74       136
           3       0.64      0.74      0.69       128
           4       0.77      0.50      0.61        40
           5       0.00      0.00      0.00         3

    accuracy                           0.68       320
   macro avg       0.35      0.33      0.34       320
weighted avg       0.66      0.68      0.66       320

Confusion Matrix:
[[  0   0   1   1   0   0]
 [  0   0   9   2   0   0]
 [  0   0 104  31   1   0]
 [  0   0  29  95   4   0]
 [  0   0   2  18  20   0]
 [  0   0   0   2   1   0]]


/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:1565: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))
/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:1565: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))
/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:1565: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))


5-Fold CV Accuracy: 0.6646


In [53]:
# ----------------------------
# 1️⃣ 라이브러리 불러오기
# ----------------------------
import numpy as np
from sklearn.model_selection import train_test_split, cross_val_score
from sklearn.preprocessing import StandardScaler
from sklearn.metrics import accuracy_score, classification_report, confusion_matrix
import xgboost as xgb

# ----------------------------
# 2️⃣ 데이터 준비
# ----------------------------
# X, y는 와인 데이터셋
# X.shape = (1119, 11), y.shape = (1119,)

# y를 0부터 시작하도록 조정
y = y - np.min(y)

# 데이터 분리 (학습 80%, 테스트 20%)
X_train, X_test, y_train, y_test = train_test_split(
    X, y, test_size=0.2, random_state=42, stratify=y
)

# 표준화 (XGBoost는 크게 영향 없지만, 안정적 학습 위해)
scaler = StandardScaler()
X_train = scaler.fit_transform(X_train)
X_test = scaler.transform(X_test)

# ----------------------------
# 3️⃣ XGBoost 모델 정의 및 학습
# ----------------------------
xgb_model = xgb.XGBClassifier(
    objective='multi:softprob',  # 다중 클래스 확률
    num_class=len(np.unique(y)),
    n_estimators=300,
    learning_rate=0.05,
    max_depth=5,
    subsample=0.8,
    colsample_bytree=0.8,
    random_state=42,
    use_label_encoder=False,
    eval_metric='mlogloss'
)

# 학습
xgb_model.fit(X_train, y_train)

# ----------------------------
# 4️⃣ 예측 및 평가
# ----------------------------
y_pred = xgb_model.predict(X_test)

accuracy = accuracy_score(y_test, y_pred)
print(f"Test Accuracy: {accuracy:.4f}\n")

print("Classification Report:")
print(classification_report(y_test, y_pred))

print("Confusion Matrix:")
print(confusion_matrix(y_test, y_pred))

# ----------------------------
# 5️⃣ 교차 검증 (선택)
# ----------------------------
cv_scores = cross_val_score(xgb_model, X_train, y_train, cv=5, scoring='accuracy')
print(f"5-Fold CV Accuracy: {cv_scores.mean():.4f}")


/usr/local/lib/python3.12/dist-packages/xgboost/training.py:183: UserWarning: [07:39:28] WARNING: /workspace/src/learner.cc:738: 
Parameters: { "use_label_encoder" } are not used.

  bst.update(dtrain, iteration=i, fobj=obj)


Test Accuracy: 0.6719

Classification Report:
              precision    recall  f1-score   support

           0       0.00      0.00      0.00         2
           1       0.50      0.09      0.15        11
           2       0.72      0.74      0.73       136
           3       0.62      0.71      0.66       128
           4       0.71      0.55      0.62        40
           5       0.50      0.33      0.40         3

    accuracy                           0.67       320
   macro avg       0.51      0.40      0.43       320
weighted avg       0.67      0.67      0.66       320

Confusion Matrix:
[[  0   0   1   1   0   0]
 [  0   1   6   4   0   0]
 [  0   0 100  35   1   0]
 [  0   1  29  91   7   0]
 [  0   0   2  15  22   1]
 [  0   0   0   1   1   1]]


/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:1565: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))
/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:1565: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))
/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:1565: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))
/usr/local/lib/python3.12/dist-packages/xgboost/t

5-Fold CV Accuracy: 0.6685
